title: "Tomylver Pentest Blog"
description: "Web / 内网 / 漏洞复现 / 工具记录"
url: "https://itomylver-alt.github.io"
baseurl: ""

theme: minima
markdown: kramdown

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
